<%inherit file="/base.mako"/>

<div class="page-grid">
  <section>
    <div class="section-head">
      <h1>Projects</h1>
      <p>Target programs generated by Codeeli.</p>
    </div>
    <div class="list-group list-group-flush codeeli-list">
      % if projects:
        % for project in projects:
          <a class="list-group-item list-group-item-action" href="/projects/${project['id']}">
            <div class="d-flex justify-content-between gap-3">
              <strong>${project['name']}</strong>
              <span class="text-secondary small">${project['ai_config_name'] or 'no AI'}</span>
            </div>
            <div class="small text-secondary mt-1">${project['workspace_dir']}</div>
            <div class="small mt-2">Recipe: ${project['recipe_name'] or 'none'}</div>
          </a>
        % endfor
      % else:
        <div class="empty-state">No projects yet. Create your first one on the right.</div>
      % endif
    </div>
  </section>

  <aside class="panel">
    <h2>New project</h2>
    <form method="post" action="/projects" class="vstack gap-3">
      <label class="form-label">Name
        <input class="form-control" name="name" required>
      </label>
      <label class="form-label">Recipe
        <select class="form-select" name="recipe_id" required>
          % for recipe in recipes:
            <option value="${recipe['id']}">${recipe['name']}</option>
          % endfor
        </select>
      </label>
      <label class="form-label">Model configuration
        <select class="form-select" name="ai_config_id" required>
          % for config in configs:
            <option value="${config['id']}">${config['name']} (${config['provider']}/${config['model']})</option>
          % endfor
        </select>
      </label>
      <label class="form-label">Workspace directory
        <input class="form-control" name="workspace_dir" placeholder="default: workspaces/project-name">
      </label>
      <label class="form-label">Program description
        <textarea class="form-control" name="prompt" rows="7"></textarea>
      </label>
      <button class="btn btn-primary" type="submit" ${'disabled' if not configs or not recipes else ''}>Create project</button>
    </form>
  </aside>
</div>
